server.servlet.contextPath=/
server.port=8848
spring.datasource.platform=mysql
# ?????
db.num=1
db.url.0=jdbc:mysql://mysql_yudao/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user=root
db.password=123456